# Generated by Django 3.0 on 2019-12-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('creation_date', models.DateTimeField()),
                ('tags', models.ManyToManyField(to='handler.Tag')),
            ],
        ),
    ]
