# Generated by Django 3.0 on 2020-01-09 12:25

from django.db import migrations


def add_tags(apps, schema_editor):
    tag = apps.get_model('handler', 'Tag')
    tag.objects.create(title='Народная')
    tag.objects.create(title='Опера')
    tag.objects.create(title='Вокал')
    tag.objects.create(title='Симфоническая')
    tag.objects.create(title='Фолк')
    tag.objects.create(title='Кантри')
    tag.objects.create(title='Шансон')
    tag.objects.create(title='Хаус')
    tag.objects.create(title='Фолк')
    tag.objects.create(title='Ска')


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_tags)
    ]
