# Generated by Django 3.0 on 2020-01-09 12:25

from django.db import migrations


def add_tags(apps, schema_editor):
    model_tag = apps.get_model('handler', 'Tag')
    tags = [
        'Народная',
        'Вокал',
        'Опера',
        'Симфоническая',
        'Фолк',
        'Кантри',
        'Шансон',
        'Хаус',
        'Фолк',
        'Ска'
    ]
    for tag in tags:
        model_tag.objects.create(title=tag)


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_tags)
    ]
