# Generated by Django 3.0 on 2019-12-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(max_length=32)),
                ('tags', models.CharField(max_length=32)),
            ],
        ),
    ]
