# Generated by Django 3.0 on 2019-12-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='chat_id',
            field=models.IntegerField(),
        ),
    ]
