# Generated by Django 3.0 on 2019-12-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0004_auto_20191228_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='tags',
        ),
        migrations.AddField(
            model_name='notification',
            name='tags',
            field=models.ManyToManyField(to='handler.Tag'),
        ),
    ]
