# Generated by Django 3.0 on 2019-12-29 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0005_auto_20191228_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='tags',
        ),
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='handler.Event'),
        ),
        migrations.AddField(
            model_name='notification',
            name='status_send',
            field=models.BooleanField(default=False),
        ),
    ]
