# Generated by Django 3.0 on 2019-12-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0006_auto_20191229_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='handled',
            field=models.BooleanField(default=False),
        ),
    ]
